# ┌─────┐┌───╮
# │     ││ ┌─╯
# │ ├─┤ ││ └─╮
# └─┘ └─┘└───╯
# MatrixChecks
#
# The changes in this file are only for organization and minor tweaks.
# Install "checks.yml" to utilize the improved cheat detection!
#
# GitHub:  https://github.com/QuantumSuite/MatrixChecks
# Discord: https://discord.gg/rjSkFyj

# Premium user credentials.
# These are obtained after messaging Matrix's developer with proof of purchase.
# Don't share this information! Your Matrix account will be terminated.
premium_user:
  user: ''
  password: ''

# Check for updates on server start.
check_update: true

# Downloads checks.yml from an external web server on server start.
# I recommend using this with MatrixChecks to automatically update the checks.
# To enable this feature, just change "cloud_config.enable: false" to "true".
# This will ignore your local checks.yml and update on every server restart!
cloud_config:
  enable: false

  # The links to download checks from.
  # You can have multiple links in case one goes down. (Only the first valid link is used)
  links:
    - 'https://raw.githubusercontent.com/QuantumSuite/MatrixChecks/main/cloud/checks.yml'

# GeyserMC support
# Enable this ONLY if you have GeyserMC for security reasons. (Bedrock support)
# To enable this feature, install Matrix on Bungee + all sub-servers and enable this option on each instance.
bungee_geysermc_support: false

# Register commands from other anticheats.
# Prevents finding the anticheat your server uses via commands.
# I recommend CommandWhitelist to block players from seeing the Matrix commands.
fake_anticheat:
  aac: false
  spartan: false

# Stops players from re-logging right after being kicked. (seconds)
# This should be increased if you don't want hackers to re-join quickly.
relog_time: 15

# Automatically disables some checks when the server TPS drops.
# This prevents some false positives for checks that require little lag.
tps_protection:
  enable: true

  # Disable checks below this number.
  min_tps: 17.0

  # If the server doesn't respond within this amount of time, cancel the check. (ms)
  lag_threshold: 750

# Logs all violations to the Matrix/logs directory.
# Recommended to enable if you are debugging/monitoring checks.
log_file: true

# Delete old Matrix log files. (days)
delete_time: 7

# Summon a lightning strike on players who are kicked via /matrix kick.
kick_strike_lightning: false

# Disables the "matrix.bypass" permission.
# Enable if you want every player to be checked.
disable_bypass_permission: false

# Time between permission cache refresh. (seconds)
# Setting this too high can cause issues with the bypass permission.
permission_refresh_interval: 120

# Disable specific components used in checks.
# Example:
# disabled_components:
#   - 'vel.ana'
disabled_components: []

# Sets a custom vl_weight for specific components.
# Example:
# custom_vl_weight:
#   - 'vel.ana:4'
custom_vl_weight: []