# MatrixChecks (CONFIG)
# The optimized checks for Matrix Anticheat, a powerful anticheat for Minecraft.
# For Matrix 5.1.1+
#
# !! NOTE !!
# THIS FILE DOES _NOT_ INCLUDE ANY CHECKS
# INSTALL "checks.yml" TO MAKE USE OF OPTIMIZATIONS
# THIS FILE ONLY INCLUDES MINOR CHANGES TO THE BASE CONFIG! 
#
# The changes in "config.yml" only include some organization,
# minor tweaks, and cloud-config already set up for MatrixChecks.
#
# --------------------------------------------
#                  Issues?
# Follow the FAQ's in README.md. (Question #3)
# --------------------------------------------
#
# GitHub: https://github.com/Encode42/MatrixChecks
# Discord: https://discord.gg/rjSkFyj

# Check for updates on server start.
check_update: true

# Reduce violations/flags triggered by players with high ping.
player_latency_protection:
  enable: true

# Downloads checks.yml from an external web server on server start.
# Of course, I recommend using the cloud-config for MatrixConfig, which is already provided.
# To enable this feature, just set "enable" to true. This will ignore your local checks.yml.
cloud_config:
  enable: false

  # The links to download from.
  # You can have multiple links here, in case a server goes down. (Only the first valid link is used)
  links:
    - 'https://raw.githubusercontent.com/Encode42/MatrixChecks/main/cloud/checks.yml'

# Time between permission cache refresh. (seconds)
permission_refresh_interval: 60

# Shows a lightning strike on players who are kicked via /matrix kick.
kick_strike_lightning: false

# If enabled, Matrix will never do any setbacks/cancels. (Silent/Ghost mode)
ghost_mode: false

# Premium user credentials.
# These are obtained after DMing RE with proof of purchase. (Don't share these!)
premium_user:
  user: ''
  password: ''

# Automatically disables some checks when the server TPS drops.
# This prevents some false positives for checks that require little lag.
tps_protection:
  enable: true

  # Disable checks below this number.
  min_tps: 17.5

  # If the server doesn't respond within this amount of time, cancel the check.
  lag_threshold: 1250

# Logs all violations to /plugins/Matrix/logs.
# Recommended to enable if you are debugging/monitoring checks.
log_file: true

# Delete old Matrix log files. (days)
delete_time: 7

# Disables the "matrix.bypass" permission.
# Enable if you want EVERYONE to be checked.
disable_bypass_permission: false

# Prevents players from relogging after being kicked. (seconds)
relog_time: 15

# Disable specific components used in checks.
# Example:
# disabled_components:
#   - 'vel.ana'
disabled_components: []

# Sets a custom vl_weight for specific components.
# Example:
# custom_vl_weight:
#   - 'vel.ana:4'
custom_vl_weight: []

# Changes the prefix for Bedrock players.
# NOTE: Must use Floodgate to change this.
#geyser_prefix: "*" # Uncomment this line to enable. (Remove the first "#")