name: Run Scripts
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "16"
          cache: "gradle"

      - name: Process scripts
        run: |
          cd scripts
          ./gradlew launch

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add variations/*.yml # cloud/*.yml
          git commit -m "Process scripts (Variations & Minifications)" || echo "No changes were found."

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}