name: Minify files
on: [push]
jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Download required modules
        run: |
          cd cloud
          npm i js-yaml

      - name: Run scripts
        run: |
          node ./github/scripts/minify.js

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add optional/*.yml cloud/*.yml
          git commit -m "Minify files" || echo "No changes were found."

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}