name: Run Scripts
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Process scripts
        run: |
          cd scripts
          ./gradlew runShadow

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add variations/* cloud/*
          git commit -m "Process scripts (Variations & Minifications)" || echo "No changes were found."

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Upload zipfile
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: MatrixChecks.zip
